debug: true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
#  datasource:
#    url: jdbc:mysql://xxx.x.x.x:3306/{db명}
#    username: {아이디}
#    password: {password}
#    driver-class-name:  com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 80
---
spring:
  profiles: local
server:
  port:8080
---
spring:
  profiles: dev
server:
  port:8081
---
spring:
  profiles: live
server:
  port:8082