debug: true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace
#---
#spring:
#  profiles: local
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
#server:
#  port: 8080
spring:
  datasource:
    url: jdbc:mysql://125.191.212.64:3307/community_test?characterEncoding=UTF-8&serverTimezone=UTC
    username: ahndy84
    password: samsung10!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
server:
  port: 80