debug: true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://125.191.212.64:3307/community_test?characterEncoding=UTF-8&serverTimezone=UTC
    username: ahndy84
    password: samsung10!
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 80
---
spring:
  profiles: local
server:
  port:8080
---
spring:
  profiles: dev
server:
  port:8081
---
spring:
  profiles: live
server:
  port:8082